sudo: false
language: node_js
node_js:
- 12.8.0
env:
  global:
  - YARN_VERSION=1.19.2
before_install:
- export PATH="$HOME/.yarn/bin:$PATH"
- |
  if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  fi
install:
- yarn install --pure-lockfile
script:
- yarn run eslint
- yarn run test
- yarn run flow
after_success:
- "./node_modules/.bin/codecov"
deploy:
  matrix:
  - provider: npm
    email: enrique.arias.cervero@gmail.com
    api_key:
      secure: Zxq9fKmUym+9QoVjmIJodlyDcTKm6/gs2P16eBwI22ysjFIXL15KeOFW4sVUSKTERNRBec3T6kMPMECiBcDupUqzNzEmE/RMoiTvPQskPSy0348nkloz6trjMg2aSECG0eCJlvbigt/NYX7pI9dV6yzO/h7nnCmKL/0LV3eSnkZpITWBOBJHHW7MX+vqied6iUX61bGkEoS1r8JthIdCocglqKMUBUNBW51e6TxDnfj/FMeJV2aJ65Pe95iPSHS16JJZZ9AwrGfDbYA2fLlhfKzejmdo6nVP98REO26nggkhp9bzgjbBU5suzxKToOCAqntQfphgZZfaErOwqpDCzqKK2QzMTUMUCrjyZDxQ2+wWoWpGASnAUqZVOmZkv4tVslE+MqqneMnXAL6IrjcuVxUGffw1CiwGnyutPz1kHGIsNS6L79duOibMx+tJKY111xskEKvQMFwRCaI9tCHBjZip36jYchAu4m0mEVf6VDYKMFiYcGUcAQDC3fSkr6607FOjsfCOPhGY+UbBnRKnrOETEfaS+8+Oa3G6avhQSVCdtEngSRjfYEEoGndgEPI2bo2yoQTlKOihLP20KqVnl8w98eBcEXkGVL7MhrPprLq/0RUXY+hvuKoFwYiD+4QIoIxJdg77xUYQVfR7BSzyUANdvFs3l8+2gI/mKDUxjEM=
    skip_cleanup: true
    on:
      tags: true
      repo: emoriarty/typescript-intl-cra
cache:
  yarn: true
  directories:
  - "~/.yarn"
  - node_modules
notifications:
  email: enrique.arias.cervero@gmail.com
