sudo: false
language: node_js
node_js:
- 12.8.0
env:
  global:
  - YARN_VERSION=1.19.2
before_install:
- export PATH="$HOME/.yarn/bin:$PATH"
- |
  if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  fi
install:
- yarn install --pure-lockfile
script:
- yarn run eslint
- yarn run test
- yarn run flow
after_success:
- "./node_modules/.bin/codecov"
deploy:
  provider: npm
  edge: true
  email: enrique.arias.cervero@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: emoriarty/typescript-intl-cra
  api_key:
    secure: ACSg2KQFWnvyEr8WJwYFlJg1Dg47m+ZxjIYqmWULllRUKqP9jjgJo1l+fpd3fJ477EzzFNVC9TpzapYrCllYmPdckrl1Ina0Fr4nnpgbd3pcCjpX9nCzo3wKhk6mLwL4WmaVeNE5oPkw/ntttn5TJixuiRD+2iQ7i7Hx7U7pRemcnrz45gcVw1DKwm3fi6x3BEcpBF4w5k+2yiHy90/pPavGzvnKpL0weVO3GOjcdzzjpMABZFafeVuiFGGijNyR3IMZWmH5b+Np8JwNsUkFuJ1KoBWs+w9ZCwQWkIgG5UmFI+cqN6/Tfld8P2w+kw6A0GY5JUmXS7IsC9yOZ90xWDLkQHHMqR1RmIh1rA7AtCK6TWj5cuof449ZlwYpoYdj2vRw/dsRNJnYqSUpeloXheWp1rNIlMPUoRHBZf2pzC6XH4WWMfulrTW5s0y9QFHZVGGnV1+kKFv7XRr9N7Olf9eMeS1Q7puMk7EweVK5xnup9daBaLsP1yX81h/ik6OE1Iv3uzmeCsykUG1na1mp7h25P9Fsbh/wQ+QRPk0UifS13ecVgBnVvIrhpq7biziMJ+o6Uq7NtIpnpoDOpgmwq6n7viBe8clmWliKlvChTYe+dep1HCMu/+vXQjBOId2tuiTHsPfUzkxCgm+FdrgkYUgeAmGqsWep3Lm1QjT5WWg=
cache:
  yarn: true
  directories:
  - "~/.yarn"
  - node_modules
notifications:
  email: enrique.arias.cervero@gmail.com
